# Cocoapods
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.3'

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target 'IPHTTPS_Demo' do

    pod 'AFNetworking'

end
